# 02-install-requirements.yaml

- hosts: all
  remote_user: kato
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - htop
          - byobu
          - net-tools
          - ebtables
          - ipset
          - open-iscsi
          - conntrack
          - socat
        state: present